### PR TITLE
Build compat layer 2023.04 by bot

### PR DESCRIPTION
**Pull request by trz42**
- uses last working gentoo commit (March 13)
- build for `aarch64` and `x86_64` for both NESSI and EESSI
- serves also as a test for `bot/check-result.sh`

### CODE REVIEW

**Comment by trz42** [comment]
bot: showconfig
- received bot command `showconfig` from `trz42` (expanded command format: `showconfig `)
- handling `showconfig` resulted in: added comment https://api.github.com/repos/NorESSI/compatibility-layer/issues/10 to show configuration

**Comment by trz42** [comment]
bot: showconfig
- received bot command `showconfig` from `trz42` (expanded command format: `showconfig `)
- handling `showconfig` resulted in: added comment https://api.github.com/repos/NorESSI/compatibility-layer/issues/10 to show configuration

**Comment by trz42** [comment]
bot: build I:eX3 A:zen2 R:11
- parsing bot command `build I:eX3 A:zen2 R:11` received from sender `trz42` failed

**Comment by trz42** [comment]
bot: build inst:eX3 arch:aarch64 repo:2023.04
bot: build inst:AWS arch:x86_64/generic repo:2023.04
- received bot command `build inst:eX3 arch:aarch64 repo:2023.04` from `trz42` (expanded command format: `build instance:eX3 architecture:aarch64 repository:2023.04`)
- received bot command `build inst:AWS arch:x86_64/generic repo:2023.04` from `trz42` (expanded command format: `build instance:AWS architecture:x86_64/generic repository:2023.04`)
- handling `build` resulted in: no jobs were prepared
- handling `build` resulted in: created jobs: 4555, 4556

**Comment by TopRichard** [comment]
bot: help
- received bot command `help` from `TopRichard` (expanded command format: `help `)
- handling `help` resulted in: 
  **How to send commands to bot instances**
  - Commands must be sent with a **new** comment (edits of existing comments are ignored).
  - A comment may contain multiple commands, one per line.
  - Every command begins at the start of a line and has the syntax `bot: COMMAND [ARGUMENTS]*`
  - Currently supported COMMANDs are: `help`, `build`, `showconfig`

**Comment by trz42** [comment]
Updated trz42/gentoo-overlay:
- removed `lmod` directory
- removed editors (vim & emacs) and htop
- line <code>Updated trz42/gentoo-overlay:
</code> is not considered to contain a bot command
- bot commands begin with `bot: `, make sure
  there is no whitespace at the beginning of a line
- line <code>- removed `lmod` directory
</code> is not considered to contain a bot command
- bot commands begin with `bot: `, make sure
  there is no whitespace at the beginning of a line
- line <code>- removed editors (vim & emacs) and htop</code> is not considered to contain a bot command
- bot commands begin with `bot: `, make sure
  there is no whitespace at the beginning of a line

**Comment by trz42** [comment]
bot: build inst:AWS arch:x86_64/generic repo:eessi-2023.04
- received bot command `build inst:AWS arch:x86_64/generic repo:eessi-2023.04` from `trz42` (expanded command format: `build instance:AWS architecture:x86_64/generic repository:eessi-2023.04`)
- handling `build` resulted in: created jobs: 4558

**Comment by trz42** [comment]
2023.04 was abandoned

**Pull request closed without merging**
